reviews = [
    {
        "user_review": "Брал для дома, вполне сойдет. Немного смутила упоковка, но работает хорошо.",
        "reviews_date": "2024-09-29",
        "star_review": 4,
        "text_len": 72,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Товар пришел вовремя, но с мелкими царапками. Всё ровно оставил себе, норм.",
        "reviews_date": "2024-10-02",
        "star_review": 4,
        "text_len": 76,
        "has_media": 1,
        "written_by_bot": 0,
    },
    {
        "user_review": "Заказывал на подарк. Коробка слегка мятая, но внутри всё цело. Буду заказывать ещё.",
        "reviews_date": "2024-11-15",
        "star_review": 5,
        "text_len": 80,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Продавец положил что-то не то. Вернули деньки, но осадок остался. Доставили быстро.",
        "reviews_date": "2024-10-19",
        "star_review": 3,
        "text_len": 81,
        "has_media": 1,
        "written_by_bot": 0,
    },
    {
        "user_review": "Ожидал болше за такие деньги. Работает норм, но выглядит дешево. Упоковка ок.",
        "reviews_date": "2024-11-10",
        "star_review": 3,
        "text_len": 78,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Покупал для радителей, говорят, что устраивает. Цвет немного отлечается.",
        "reviews_date": "2024-09-30",
        "star_review": 4,
        "text_len": 76,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Доставка была не самой быстрой, но товар норм. Опечатки в инструкции удивили.",
        "reviews_date": "2024-10-05",
        "star_review": 4,
        "text_len": 78,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Все работает, но коробка слегка разорвана была. Не кретично, но неприятно.",
        "reviews_date": "2024-10-20",
        "star_review": 4,
        "text_len": 76,
        "has_media": 1,
        "written_by_bot": 0,
    },
    {
        "user_review": "В целом понравилось, хотя провод коротковат. Буду брать у этого продавца еше.",
        "reviews_date": "2024-09-25",
        "star_review": 5,
        "text_len": 74,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "За свои деньги норм. Не супер качесвенно, но я и не ожидал. Работает стабильно.",
        "reviews_date": "2024-09-26",
        "star_review": 4,
        "text_len": 78,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Товар пришёл быстро, но каробка немного помята. Работет хорошо.",
        "reviews_date": "2024-10-01",
        "star_review": 4,
        "text_len": 70,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Очень даволен, всё как описано. Правда, инструкция не на том язике.",
        "reviews_date": "2024-10-07",
        "star_review": 5,
        "text_len": 72,
        "has_media": 1,
        "written_by_bot": 0,
    },
    {
        "user_review": "За такие деньги товар просто супер. Удобный и крассывый дезайн.",
        "reviews_date": "2024-10-12",
        "star_review": 5,
        "text_len": 68,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Привезли с задержкой, но качеством доволен. Обещаного цвета не было.",
        "reviews_date": "2024-10-14",
        "star_review": 4,
        "text_len": 74,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Упоковка была вскрыта, но товар целый. Продавец адекватный.",
        "reviews_date": "2024-10-16",
        "star_review": 4,
        "text_len": 63,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Это лутшая покупка за последнее врема. Однозначно советую.",
        "reviews_date": "2024-10-18",
        "star_review": 5,
        "text_len": 65,
        "has_media": 1,
        "written_by_bot": 0,
    },
    {
        "user_review": "Дешево и сердито, но меня устроило. Заказал ещё раз для друга.",
        "reviews_date": "2024-10-20",
        "star_review": 4,
        "text_len": 64,
        "has_media": 1,
        "written_by_bot": 0,
    },
    {
        "user_review": "Продавец положил подарок. Очень приятный сюрприз, но был дефект.",
        "reviews_date": "2024-10-22",
        "star_review": 5,
        "text_len": 67,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Пришёл вовремя, но крраска местами потёрта. Работает, меня устраивает.",
        "reviews_date": "2024-10-25",
        "star_review": 4,
        "text_len": 71,
        "has_media": 1,
        "written_by_bot": 0,
    },
    {
        "user_review": "Работает, как написанно, но шумноват. За такие деньги не плохо.",
        "reviews_date": "2024-10-27",
        "star_review": 4,
        "text_len": 65,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Доставка норм, но корбка разорвана. Товар целый, ставлю 4 звезды.",
        "reviews_date": "2024-10-29",
        "star_review": 4,
        "text_len": 66,
        "has_media": 1,
        "written_by_bot": 0,
    },
    {
        "user_review": "Немного поцарапаный, но работает исправно. Претензий нет.",
        "reviews_date": "2024-10-31",
        "star_review": 4,
        "text_len": 62,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Купил другу, он доволен. Упаковка могла бы быть чучуть лучше.",
        "reviews_date": "2024-11-02",
        "star_review": 4,
        "text_len": 63,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Инструкция отсутсвует, но я разобрался сам. Работает отлично.",
        "reviews_date": "2024-11-04",
        "star_review": 4,
        "text_len": 65,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Продукт хороший, но доставку задержали. В целом доволен, рекомендую.",
        "reviews_date": "2024-11-06",
        "star_review": 4,
        "text_len": 70,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Положили не то, но заменили быстро. Остался довольный. Молодцы!",
        "reviews_date": "2024-11-08",
        "star_review": 4,
        "text_len": 62,
        "has_media": 1,
        "written_by_bot": 0,
    },
    {
        "user_review": "Шумный, но работает. Не идеально, но свои функции выпоняет.",
        "reviews_date": "2024-11-10",
        "star_review": 4,
        "text_len": 58,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Коробка была грязная, но товар как новый. Устраивает.",
        "reviews_date": "2024-11-12",
        "star_review": 4,
        "text_len": 57,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Один болтик был не на месте. Быстро поправил, всё заработоло.",
        "reviews_date": "2024-11-14",
        "star_review": 5,
        "text_len": 65,
        "has_media": 1,
        "written_by_bot": 0,
    },
    {
        "user_review": "Небольшие огрехи в отделке, но работает нормально. Цена оправданна.",
        "reviews_date": "2024-11-16",
        "star_review": 4,
        "text_len": 65,
        "has_media": 0,
        "written_by_bot": 0,
    },
        {
        "user_review": "Брал для ремонта, толька начал использовать, но пока доволен.",
        "reviews_date": "2024-10-15",
        "star_review": 4,
        "text_len": 68,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Товар хороший, но к упаковке претензии - была мятая корбка.",
        "reviews_date": "2024-11-03",
        "star_review": 4,
        "text_len": 69,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Прост в использовании, но инструкции были не очен четкие.",
        "reviews_date": "2024-12-01",
        "star_review": 3,
        "text_len": 63,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Работает, как заявленно. Понравилось, что есть все нужные фунцкции.",
        "reviews_date": "2024-09-19",
        "star_review": 5,
        "text_len": 77,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Неудобная доставка, пришлось ждать два дня долше, чем планировал.",
        "reviews_date": "2024-11-25",
        "star_review": 3,
        "text_len": 77,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Устройство работает хорошо, но после вскрытия корбки был запах.",
        "reviews_date": "2024-10-09",
        "star_review": 4,
        "text_len": 72,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Купил недавно, пока нареканий нет, только инстуркция сложная.",
        "reviews_date": "2024-12-18",
        "star_review": 4,
        "text_len": 70,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Отличное качество, только подстветка могла быть чуть ярче.",
        "reviews_date": "2024-11-30",
        "star_review": 4,
        "text_len": 67,
        "has_media": 0,
        "written_by_bot": 0,
    },
        {
        "user_review": "Купил холодильник, работает тихо. Но уплотнитель на двери немного отохдит.",
        "reviews_date": "2024-08-14",
        "star_review": 4,
        "text_len": 82,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Микроволновка хорошая, но немного шатается на столе. Не критично, но не приянтно.",
        "reviews_date": "2024-09-10",
        "star_review": 4,
        "text_len": 87,
        "has_media": 1,
        "written_by_bot": 0,
    },
    {
        "user_review": "Смартфон отличный, но зарядка в комплекте идет слабовата для бфстрой зарядки.",
        "reviews_date": "2024-11-20",
        "star_review": 4,
        "text_len": 91,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Купил кофеварку, кофе получается вкусный, но контенейр для воды маловат.",
        "reviews_date": "2024-10-22",
        "star_review": 5,
        "text_len": 82,
        "has_media": 1,
        "written_by_bot": 0,
    },
    {
        "user_review": "Пылесос мощный, но шнур коротковат, приходится часто перекюлючаться.",
        "reviews_date": "2024-12-01",
        "star_review": 4,
        "text_len": 85,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Умные часы удобные, но не сразу разобрался с настройкай увкдомлений.",
        "reviews_date": "2024-11-15",
        "star_review": 4,
        "text_len": 86,
        "has_media": 1,
        "written_by_bot": 0,
    },
    {
        "user_review": "Триммер нормальный, но рукоятка оказалась немного тонкой для мрйе руки.",
        "reviews_date": "2024-08-29",
        "star_review": 3,
        "text_len": 83,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Наушники звучат отлично, но амбшюры не очень удобные для долгого использовпния.",
        "reviews_date": "2024-09-07",
        "star_review": 4,
        "text_len": 91,
        "has_media": 1,
        "written_by_bot": 0,
    },
    {
        "user_review": "Стиральная машина стирает хорошо, но при отжиме немного шевелится.",
        "reviews_date": "2024-10-04",
        "star_review": 4,
        "text_len": 78,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Монитор отличного качества, но кабель HDMI в комплекте коротки.",
        "reviews_date": "2024-09-25",
        "star_review": 5,
        "text_len": 74,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Игровая мышь удобная, но софт для настройки макросов не интуютивный.",
        "reviews_date": "2024-11-12",
        "star_review": 4,
        "text_len": 78,
        "has_media": 1,
        "written_by_bot": 0,
    },
    {
        "user_review": "Коврик для мыши нормальный, но края начали махрится через мпесяц.",
        "reviews_date": "2024-08-30",
        "star_review": 3,
        "text_len": 77,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Чехол для телефона подошел, но окошко для камеры сдвинуто немного.",
        "reviews_date": "2024-10-17",
        "star_review": 3,
        "text_len": 76,
        "has_media": 1,
        "written_by_bot": 0,
    },
    {
        "user_review": "Книгу упаковали плохо, уголки помялись, но сама книга интересная.",
        "reviews_date": "2024-11-03",
        "star_review": 4,
        "text_len": 72,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Лампа светит ярко, но выключатель расположон неудобно на шнуре.",
        "reviews_date": "2024-12-20",
        "star_review": 4,
        "text_len": 79,
        "has_media": 1,
        "written_by_bot": 0,
    },
    {
        "user_review": "Купил чайник, кипятит быстро, но крышка открывается не до конца.",
        "reviews_date": "2024-09-11",
        "star_review": 4,
        "text_len": 76,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Массажер работает отлично, но нагрев включается слишком медленно.",
        "reviews_date": "2024-11-29",
        "star_review": 5,
        "text_len": 72,
        "has_media": 1,
        "written_by_bot": 0,
    },
    {
        "user_review": "Утюг нагревается быстро, но есть небольшой запах пластика при работе.",
        "reviews_date": "2024-08-20",
        "star_review": 4,
        "text_len": 79,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
        "user_review": "Гриль хороший, но сложно чистить решетку, так как прилипает жир.",
        "reviews_date": "2024-10-06",
        "star_review": 4,
        "text_len": 76,
        "has_media": 1,
        "written_by_bot": 0,
    },
    {
        "user_review": "Тостер работает нормально, но крутилки слишком тугие для регулировки.",
        "reviews_date": "2024-12-08",
        "star_review": 3,
        "text_len": 75,
        "has_media": 0,
        "written_by_bot": 0,
    },
    {
    "user_review": "Чайник хороший, но крышка чут-чуть заедает, и вода долго наливается.",
    "reviews_date": "2024-12-13",
    "star_review": 4,
    "text_len": 73,
    "has_media": 0,
    "written_by_bot": 0
    },
    {
    "user_review": "Принтер печатает хорошо, но иногда картридж не совсем плотнно входит.",
    "reviews_date": "2024-11-21",
    "star_review": 4,
    "text_len": 69,
    "has_media": 0,
    "written_by_bot": 0
    },
    {
    "user_review": "Смартфон нормальный, но экран немого тускловат.",
    "reviews_date": "2024-10-30",
    "star_review": 3,
    "text_len": 55,
    "has_media": 1,
    "written_by_bot": 0
    },
]