fake_reviews = [
    {
        "user_review": "Товар просто замечательный! Рекомендую всем друзьям.",
        "reviews_date": "2024-09-29",
        "star_review": 5,
        "text_len": 59,
        "has_media": False,
        "written_by_bot": 1,
    },
    {
        "user_review": "Не ожидал, что будет так классно. Восхитительная покупка!",
        "reviews_date": "2024-09-28",
        "star_review": 5,
        "text_len": 64,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Использую ежедневно и не жалею о покупке. Восхитительно!",
        "reviews_date": "2024-09-27",
        "star_review": 5,
        "text_len": 65,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Покупка стоила моих ожиданий. Каждому рекомендую!",
        "reviews_date": "2024-09-26",
        "star_review": 5,
        "text_len": 58,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Супер продукт! Полностью удовлетворен и рекомендую!",
        "reviews_date": "2024-09-25",
        "star_review": 5,
        "text_len": 62,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Крутой товар, хорошее качество по отличной цене!",
        "reviews_date": "2024-09-24",
        "star_review": 5,
        "text_len": 60,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Думал, не получится, но вот и результат! Огромное спасибо!",
        "reviews_date": "2024-09-23",
        "star_review": 5,
        "text_len": 70,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Бесподобное качество! Покупайте, не пожалеете!",
        "reviews_date": "2024-09-22",
        "star_review": 5,
        "text_len": 55,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Выбор оказался успешным. Проект супер, рекомендую всем!",
        "reviews_date": "2024-09-21",
        "star_review": 5,
        "text_len": 66,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Здорово, что купил! Нереально крутая вещь, рекомендую!",
        "reviews_date": "2024-09-20",
        "star_review": 5,
        "text_len": 64,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Данный продукт оказался незаменимым. Советую всем!",
        "reviews_date": "2024-09-19",
        "star_review": 5,
        "text_len": 63,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Скажу одно: мечта! Удивительное решение для повседневной жизни.",
        "reviews_date": "2024-09-18",
        "star_review": 5,
        "text_len": 82,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Отличная покупка, на все 100 процентов! Всегда буду брать.",
        "reviews_date": "2024-09-17",
        "star_review": 5,
        "text_len": 69,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Просто находка! Доволен, как слон! Рекомендую всем.",
        "reviews_date": "2024-09-16",
        "star_review": 5,
        "text_len": 64,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Рад, что решился на покупку. Отличное качество и цена!",
        "reviews_date": "2024-09-15",
        "star_review": 5,
        "text_len": 65,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Просто супер! Лучшая инвестиция в мои покупки.",
        "reviews_date": "2024-09-14",
        "star_review": 5,
        "text_len": 58,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Нереально довольна покупкой! Всем настоятельно рекомендую!",
        "reviews_date": "2024-09-13",
        "star_review": 5,
        "text_len": 68,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Понравился с первого взгляда. За такие деньги, просто отлично!",
        "reviews_date": "2024-09-12",
        "star_review": 5,
        "text_len": 72,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Круто! Полностью оправданы все ожидания! Советую!",
        "reviews_date": "2024-09-11",
        "star_review": 5,
        "text_len": 63,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Что-то невероятное! Я в восторге от своей покупки!",
        "reviews_date": "2024-09-10",
        "star_review": 5,
        "text_len": 56,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Этот смартфон действительно удивил меня своим качеством. Камера делает потрясающие снимки даже при слабом освещении. Рекомендую!",
        "reviews_date": "2024-09-30",
        "star_review": 5,
        "text_len": 139,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Блендер, который я купил, превзошел все мои ожидания. Легко справляется даже с твердыми ингредиентами. Рекомендую всем, кто любит готовить.",
        "reviews_date": "2024-09-29",
        "star_review": 5,
        "text_len": 147,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Очень доволен своей покупкой - стильные и удобные кроссовки. Подходят под любой стиль одежды. Мягкая подошва обеспечивает комфорт при ходьбе.",
        "reviews_date": "2024-09-28",
        "star_review": 5,
        "text_len": 151,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Покупал этот увлажнитель воздуха для своей спальни. Он работает тихо и эффективно, создавая идеальные условия для сна. Настоятельно рекомендую!",
        "reviews_date": "2024-09-27",
        "star_review": 5,
        "text_len": 140,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Собирал этот конструктор вместе с детьми. Хорошее качество деталей и интересные задачи. Дети в восторге от своего творчества!",
        "reviews_date": "2024-09-26",
        "star_review": 5,
        "text_len": 135,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Купил этот чайник, очень быстро кипятит воду и имеет стильный дизайн. Легко чистится, что тоже большой плюс. Полностью доволен своей покупкой!",
        "reviews_date": "2024-09-25",
        "star_review": 5,
        "text_len": 139,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Этот гель для душа обладает потрясающим ароматом и нежно очищает кожу. Удивительный выбор для утреннего ритуала. Чувствую себя великолепно каждый раз!",
        "reviews_date": "2024-09-24",
        "star_review": 5,
        "text_len": 139,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Покупка этой книги была лучшим решением! Интересный сюжет и персонажи, от которых невозможно оторваться. Рекомендую всем любителям фантастики.",
        "reviews_date": "2024-09-23",
        "star_review": 5,
        "text_len": 142,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Этот инструмент значительно упрощает процесс работы. Легкий и удобный в использовании, это must-have для любой мастерской.",
        "reviews_date": "2024-09-22",
        "star_review": 5,
        "text_len": 135,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Пользуюсь этой маской для лица уже несколько недель. Кожа стала гладкой и увлажненной. Видимый результат гарантирован, настоятельно рекомендую всем!",
        "reviews_date": "2024-09-21",
        "star_review": 5,
        "text_len": 148,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Эта игровая консоль подарила мне множество часов удовольствия. Играю во множество игр и наслаждаюсь отличной графикой!",
        "reviews_date": "2024-09-20",
        "star_review": 5,
        "text_len": 135,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Приобрел этот органайзер для своего рабочего стола, стал гораздо меньше беспорядка. Красивый и функциональный, отлично вписался в интерьер.",
        "reviews_date": "2024-09-19",
        "star_review": 5,
        "text_len": 145,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Эта сумка просто находка! Стильная, вместительная и при этом легкая. Подходит как для работы, так и для прогулок по городу.",
        "reviews_date": "2024-09-18",
        "star_review": 5,
        "text_len": 145,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Потрясающий набор инструментов для домашнего выполнения работ. Все необходимые элементы на месте, качество на высоте. Я в полном восторге!",
        "reviews_date": "2024-09-17",
        "star_review": 5,
        "text_len": 142,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Никогда не думал, что могу так наслаждаться приготовлением пищи. Этот кухонный процессор невероятно удобен и экономит время. Рекомендую всем!",
        "reviews_date": "2024-09-16",
        "star_review": 5,
        "text_len": 144,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Этот подстаканник просто лучший! Он держит напитки в тепле и выглядит очень стильно. Подарил всем своим друзьям, все в восторге!",
        "reviews_date": "2024-09-15",
        "star_review": 5,
        "text_len": 142,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Просто чудесный аромат этого парфюма! Долго держится и подходит для любого события. Каждый раз, когда я его наношу, получаю комплименты.",
        "reviews_date": "2024-09-14",
        "star_review": 5,
        "text_len": 139,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Эти дизайнерские часы покорили меня с первого взгляда. Качество на высоте, стильный внешний вид, точно стоят своих денег!",
        "reviews_date": "2024-09-13",
        "star_review": 5,
        "text_len": 138,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Этот товар просто потрясающий! Он идеально подходит для моих нужд и полностью оправдал мои ожидания. Качество на высоте, рекомендую всем!",
        "reviews_date": "2024-10-01",
        "star_review": 5,
        "text_len": 98,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Не могу нарадоваться этой покупке! Товар очень удобный и функциональный, работает без нареканий. Доставка была быстрой, спасибо магазину!",
        "reviews_date": "2024-09-30",
        "star_review": 5,
        "text_len": 106,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Отличное качество, стильный дизайн, удобный в использовании. Я очень довольна этой покупкой и рекомендую ее всем!",
        "reviews_date": "2024-09-29",
        "star_review": 5,
        "text_len": 86,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Товар превосходит все ожидания! Функциональность на высоте, работает без сбоев. Довольна покупкой, рекомендую!",
        "reviews_date": "2024-09-28",
        "star_review": 5,
        "text_len": 83,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Замечательный товар! Качество отличное, цена приемлемая. Рекомендую всем, кто ищет качественный продукт!",
        "reviews_date": "2024-09-27",
        "star_review": 5,
        "text_len": 89,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар соответствует описанию, работает отлично, без нареканий. Доставка была быстрой. Я очень доволен!",
        "reviews_date": "2024-09-26",
        "star_review": 5,
        "text_len": 84,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Отличный товар, рекомендую! Качество на высоте, цена доступная. Пользуюсь уже несколько месяцев, никаких проблем.",
        "reviews_date": "2024-09-25",
        "star_review": 5,
        "text_len": 92,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Прекрасный товар! Отвечает всем моим требованиям. Спасибо магазину за быструю доставку.",
        "reviews_date": "2024-09-24",
        "star_review": 5,
        "text_len": 73,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар просто супер! Отличный дизайн, высокое качество, удобный в использовании. Я очень рада этой покупке!",
        "reviews_date": "2024-09-23",
        "star_review": 5,
        "text_len": 88,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Не разочаровался в этом товаре! Соответствует всем заявленным характеристикам, работает без проблем. Рекомендую!",
        "reviews_date": "2024-09-22",
        "star_review": 5,
        "text_len": 91,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Покупкой довольна! Товар качественный, соответствует описанию. Доставка была быстрой, спасибо магазину!",
        "reviews_date": "2024-09-21",
        "star_review": 5,
        "text_len": 88,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар оправдал все мои ожидания! Качество отличное, дизайн стильный, работает без нареканий. Рекомендую!",
        "reviews_date": "2024-09-20",
        "star_review": 5,
        "text_len": 94,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Отличный товар! Качество на высоте, цена доступная. Пользуюсь уже несколько месяцев, никаких проблем.",
        "reviews_date": "2024-09-19",
        "star_review": 5,
        "text_len": 89,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар просто супер! Рекомендую всем! Качество отличное, цена приемлемая. Доставка была быстрой.",
        "reviews_date": "2024-09-18",
        "star_review": 5,
        "text_len": 83,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар соответствует описанию, работает отлично. Доставка была быстрой, все отлично!",
        "reviews_date": "2024-09-17",
        "star_review": 5,
        "text_len": 75,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Качество товара на высоте, дизайн стильный, работает без нареканий. Очень довольна покупкой!",
        "reviews_date": "2024-09-16",
        "star_review": 5,
        "text_len": 84,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Товар превосходит все ожидания! Рекомендую всем, кто ищет качественный продукт!",
        "reviews_date": "2024-09-15",
        "star_review": 5,
        "text_len": 71,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Отличный товар! Пользуюсь уже несколько месяцев, никаких проблем. Рекомендую!",
        "reviews_date": "2024-09-14",
        "star_review": 5,
        "text_len": 73,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар соответствует описанию, работает отлично, доставка была быстрой. Спасибо!",
        "reviews_date": "2024-09-13",
        "star_review": 5,
        "text_len": 77,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Покупкой довольна! Товар качественный, соответствует описанию. Рекомендую!",
        "reviews_date": "2024-09-12",
        "star_review": 5,
        "text_len": 68,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Этот товар - настоящая находка! Он идеально подходит для моих нужд и превзошел все мои ожидания. Рекомендую всем!",
        "reviews_date": "2024-10-01",
        "star_review": 5,
        "text_len": 82,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Не могу нарадоваться этой покупке! Товар очень качественный, стильный и удобный в использовании. Довольна на все сто!",
        "reviews_date": "2024-09-30",
        "star_review": 5,
        "text_len": 92,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Отличный товар! Превзошел все мои ожидания. Качество на высоте, работает без нареканий. Спасибо магазину!",
        "reviews_date": "2024-09-29",
        "star_review": 5,
        "text_len": 93,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Замечательный товар! Отличный дизайн, удобный в использовании, работает как часы. Рекомендую всем!",
        "reviews_date": "2024-09-28",
        "star_review": 5,
        "text_len": 86,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар просто супер! Я очень довольна покупкой, рекомендую всем, кто ищет качественный продукт.",
        "reviews_date": "2024-09-27",
        "star_review": 5,
        "text_len": 85,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Не разочаровался в этом товаре! Он соответствует всем заявленным характеристикам, работает отлично.",
        "reviews_date": "2024-09-26",
        "star_review": 5,
        "text_len": 83,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Прекрасный товар! Я очень довольна этой покупкой, рекомендую всем, кто ищет стильный и функциональный продукт.",
        "reviews_date": "2024-09-25",
        "star_review": 5,
        "text_len": 99,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Отличный товар! Качество на высоте, дизайн стильный, работает без нареканий. Довольна покупкой!",
        "reviews_date": "2024-09-24",
        "star_review": 5,
        "text_len": 84,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар соответствует описанию, работает отлично, без нареканий. Доставка была быстрой, спасибо магазину!",
        "reviews_date": "2024-09-23",
        "star_review": 5,
        "text_len": 93,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Прекрасный товар! Я очень довольна этой покупкой, рекомендую всем, кто ищет качественный и стильный продукт.",
        "reviews_date": "2024-09-22",
        "star_review": 5,
        "text_len": 99,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Товар оправдал все мои ожидания! Качество отличное, дизайн стильный, работает без нареканий. Спасибо!",
        "reviews_date": "2024-09-21",
        "star_review": 5,
        "text_len": 89,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Не разочаровался в этом товаре! Он соответствует всем заявленным характеристикам, работает отлично. Рекомендую!",
        "reviews_date": "2024-09-20",
        "star_review": 5,
        "text_len": 91,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Отличный товар! Качество на высоте, работает без нареканий. Доставка была быстрой, спасибо магазину!",
        "reviews_date": "2024-09-19",
        "star_review": 5,
        "text_len": 89,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар просто супер! Я очень довольна этой покупкой, рекомендую всем, кто ищет качественный и стильный продукт.",
        "reviews_date": "2024-09-18",
        "star_review": 5,
        "text_len": 99,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Замечательный товар! Отличный дизайн, удобный в использовании, работает как часы. Довольна покупкой!",
        "reviews_date": "2024-09-17",
        "star_review": 5,
        "text_len": 86,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар соответствует описанию, работает отлично, без нареканий. Доставка была быстрой, спасибо магазину!",
        "reviews_date": "2024-09-16",
        "star_review": 5,
        "text_len": 93,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Прекрасный товар! Я очень довольна этой покупкой, рекомендую всем, кто ищет качественный и стильный продукт.",
        "reviews_date": "2024-09-15",
        "star_review": 5,
        "text_len": 99,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Товар оправдал все мои ожидания! Качество отличное, дизайн стильный, работает без нареканий. Рекомендую!",
        "reviews_date": "2024-09-14",
        "star_review": 5,
        "text_len": 94,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Не разочаровался в этом товаре! Он соответствует всем заявленным характеристикам, работает отлично. Спасибо!",
        "reviews_date": "2024-09-13",
        "star_review": 5,
        "text_len": 89,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Отличный товар! Качество на высоте, работает без нареканий. Доставка была быстрой, спасибо магазину!",
        "reviews_date": "2024-09-12",
        "star_review": 5,
        "text_len": 89,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар просто супер! Я очень довольна этой покупкой, рекомендую всем, кто ищет качественный и стильный продукт.",
        "reviews_date": "2024-09-11",
        "star_review": 5,
        "text_len": 99,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Замечательный товар! Отличный дизайн, удобный в использовании, работает как часы. Довольна покупкой!",
        "reviews_date": "2024-09-10",
        "star_review": 5,
        "text_len": 86,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар соответствует описанию, работает отлично, без нареканий. Доставка была быстрой, спасибо магазину!",
        "reviews_date": "2024-09-09",
        "star_review": 5,
        "text_len": 93,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Прекрасный товар! Я очень довольна этой покупкой, рекомендую всем, кто ищет качественный и стильный продукт.",
        "reviews_date": "2024-09-08",
        "star_review": 5,
        "text_len": 99,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Товар оправдал все мои ожидания! Качество отличное, дизайн стильный, работает без нареканий. Рекомендую!",
        "reviews_date": "2024-09-07",
        "star_review": 5,
        "text_len": 94,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Не разочаровался в этом товаре! Он соответствует всем заявленным характеристикам, работает отлично. Спасибо!",
        "reviews_date": "2024-09-06",
        "star_review": 5,
        "text_len": 89,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Отличный товар! Качество на высоте, работает без нареканий. Доставка была быстрой, спасибо магазину!",
        "reviews_date": "2024-09-05",
        "star_review": 5,
        "text_len": 89,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар просто супер! Я очень довольна этой покупкой, рекомендую всем, кто ищет качественный и стильный продукт.",
        "reviews_date": "2024-09-04",
        "star_review": 5,
        "text_len": 99,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Замечательный товар! Отличный дизайн, удобный в использовании, работает как часы. Довольна покупкой!",
        "reviews_date": "2024-09-03",
        "star_review": 5,
        "text_len": 86,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар соответствует описанию, работает отлично, без нареканий. Доставка была быстрой, спасибо магазину!",
        "reviews_date": "2024-09-02",
        "star_review": 5,
        "text_len": 93,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Прекрасный товар! Я очень довольна этой покупкой, рекомендую всем, кто ищет качественный и стильный продукт.",
        "reviews_date": "2024-09-01",
        "star_review": 5,
        "text_len": 99,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Товар оправдал все мои ожидания! Качество отличное, дизайн стильный, работает без нареканий. Рекомендую!",
        "reviews_date": "2024-08-31",
        "star_review": 5,
        "text_len": 94,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Не разочаровался в этом товаре! Он соответствует всем заявленным характеристикам, работает отлично. Спасибо!",
        "reviews_date": "2024-08-30",
        "star_review": 5,
        "text_len": 89,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Отличный товар! Качество на высоте, работает без нареканий. Доставка была быстрой, спасибо магазину!",
        "reviews_date": "2024-08-29",
        "star_review": 5,
        "text_len": 89,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар просто супер! Я очень довольна этой покупкой, рекомендую всем, кто ищет качественный и стильный продукт.",
        "reviews_date": "2024-08-28",
        "star_review": 5,
        "text_len": 99,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Замечательный товар! Отличный дизайн, удобный в использовании, работает как часы. Довольна покупкой!",
        "reviews_date": "2024-08-27",
        "star_review": 5,
        "text_len": 86,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар соответствует описанию, работает отлично, без нареканий. Доставка была быстрой, спасибо магазину!",
        "reviews_date": "2024-08-26",
        "star_review": 5,
        "text_len": 93,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Прекрасный товар! Я очень довольна этой покупкой, рекомендую всем, кто ищет качественный и стильный продукт.",
        "reviews_date": "2024-08-25",
        "star_review": 5,
        "text_len": 99,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Качество товара просто на высоте! Теперь буду заказывать только здесь.",
        "reviews_date": "2024-11-19",
        "star_review": 5,
        "text_len": 63,
        "written_by_bot": True,
        "has_media": False,
    },
    {
        "user_review": "Получил заказ очень быстро. Упаковка идеальная, товар отличный!",
        "reviews_date": "2024-11-18",
        "star_review": 5,
        "text_len": 58,
        "written_by_bot": True,
        "has_media": True,
    },
    {
        "user_review": "Невероятно удобный интерфейс сайта, всё нашёл за пару минут.",
        "reviews_date": "2024-11-17",
        "star_review": 5,
        "text_len": 59,
        "written_by_bot": True,
        "has_media": False,
    },
    {
        "user_review": "Это просто находка! Ассортимент товаров огромный, а цены приятные.",
        "reviews_date": "2024-11-16",
        "star_review": 5,
        "text_len": 60,
        "written_by_bot": True,
        "has_media": False,
    },
    {
        "user_review": "Друзья порекомендовали этот магазин, и я не пожалел. Всё супер!",
        "reviews_date": "2024-11-15",
        "star_review": 5,
        "text_len": 55,
        "written_by_bot": True,
        "has_media": True,
    },
    {
        "user_review": "Сервис просто космос! Приятно, когда о клиентах так заботятся.",
        "reviews_date": "2024-11-14",
        "star_review": 5,
        "text_len": 57,
        "written_by_bot": True,
        "has_media": False,
    },
    {
        "user_review": "Получил товар вовремя, качество полностью соответствует описанию.",
        "reviews_date": "2024-11-13",
        "star_review": 5,
        "text_len": 60,
        "written_by_bot": True,
        "has_media": True,
    },
    {
        "user_review": "Лучший выбор для тех, кто ценит своё время и деньги. Советую!",
        "reviews_date": "2024-11-12",
        "star_review": 5,
        "text_len": 58,
        "written_by_bot": True,
        "has_media": False,
    },
    {
        "user_review": "Заказал впервые, но явно не в последний раз. Очень доволен.",
        "reviews_date": "2024-11-11",
        "star_review": 5,
        "text_len": 56,
        "written_by_bot": True,
        "has_media": True,
    },
    {
        "user_review": "Пожалуй, лучшее место для онлайн-покупок. Всё на высшем уровне!",
        "reviews_date": "2024-11-10",
        "star_review": 5,
        "text_len": 60,
        "written_by_bot": True,
        "has_media": True,
    },
    {
        "user_review": "Отличная куртка! Согревает даже в сильный мороз, а выглядит стильно. Качество пошива на высоте, рекомендую.",
        "reviews_date": "2024-09-29",
        "star_review": 5,
        "text_len": 65,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Телевизор просто супер! Изображение яркое, цвета сочные. Звук мощный, звук не режет уши. Очень доволен покупкой.",
        "reviews_date": "2024-09-29",
        "star_review": 5,
        "text_len": 77,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Эта шапка – просто находка! Уютно сидит на голове, отлично держит тепло. Прекрасно сочетается с любой одеждой.",
        "reviews_date": "2024-09-29",
        "star_review": 5,
        "text_len": 61,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Стиральная машина работает просто идеально! Стирка качественная, бельё чистейшее. Экономит время и силы.",
        "reviews_date": "2024-09-28",
        "star_review": 5,
        "text_len": 62,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Холодильник просто замечательный! Компактный, вместительный, все продукты хранятся в идеальном состоянии. Покупайте смело!",
        "reviews_date": "2024-09-28",
        "star_review": 5,
        "text_len": 62,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Отличный пылесос! Мощный, быстро убирает мусор, даже с труднодоступных мест. Работает тихо.",
        "reviews_date": "2024-09-28",
        "star_review": 5,
        "text_len": 55,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Ноутбук - просто находка для работы! Быстрый, лёгкий, всё работает безупречно. Рекомендую!",
        "reviews_date": "2024-09-27",
        "star_review": 5,
        "text_len": 52,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Отличный телефон! Качественная камера, быстрый процессор, все функции работают идеально.",
        "reviews_date": "2024-09-27",
        "star_review": 5,
        "text_len": 51,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Этот смарт-часы – просто супер! Оперативно работают, функциональность поражает, отличный выбор!",
        "reviews_date": "2024-09-27",
        "star_review": 5,
        "text_len": 59,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Умные колонки - идеальный выбор для дома! Звук шикарный, все функции понятны и удобны в использовании.",
        "reviews_date": "2024-09-27",
        "star_review": 5,
        "text_len": 62,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Это самый удобный кухонный комбайн! Занимает мало места, справляется с любыми задачами. Отлично справляется с приготовлением!",
        "reviews_date": "2024-09-26",
        "star_review": 5,
        "text_len": 60,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Сейф - очень надёжный! Качество материалов отличное, защита на уровне. За свою цену - лучший вариант.",
        "reviews_date": "2024-09-26",
        "star_review": 5,
        "text_len": 59,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Эта куртка невероятная! Согревает даже в самые холодные дни, отлично сидит и выглядит стильно. Качество пошива на высшем уровне, настоящая находка!",
        "reviews_date": "2024-09-30",
        "star_review": 5,
        "text_len": 82,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Телевизор просто потрясающий! Изображение яркое и четкое, звук мощный и объемный. Смотреть фильмы - одно удовольствие. Советую всем!",
        "reviews_date": "2024-09-30",
        "star_review": 5,
        "text_len": 79,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Шапка — просто идеальна! Согревает отлично, к тому же, очень стильно выглядит. Качество меха превосходное, рекомендую!",
        "reviews_date": "2024-09-30",
        "star_review": 5,
        "text_len": 66,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Стиральная машина работает бесперебойно! Стирка качественная, бельё остается чистым и свежим. Экономит время и силы. Рекомендую!",
        "reviews_date": "2024-09-29",
        "star_review": 5,
        "text_len": 76,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Этот холодильник - находка! Вместительный, сохраняет продукты свежими, а дизайн стильный. Отличная покупка!",
        "reviews_date": "2024-09-29",
        "star_review": 5,
        "text_len": 62,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Ноутбук просто супер! Быстрый, легкий, с отличной производительностью. Работа за компьютером - одно удовольствие! Рекомендую!",
        "reviews_date": "2024-09-29",
        "star_review": 5,
        "text_len": 67,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Телевизор превзошел все ожидания! Яркое изображение, звук просто потрясающий! Все функции интуитивно понятны и удобны в использовании.",
        "reviews_date": "2024-09-29",
        "star_review": 5,
        "text_len": 77,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Умные часы - отличная покупка! Функциональные, удобные в использовании, быстро реагируют. Очень стильно смотрятся.",
        "reviews_date": "2024-09-29",
        "star_review": 5,
        "text_len": 68,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Пылесос мощный, справляется с любой грязью и пылью. Убирает быстро и эффективно, а главное - очень тихий.",
        "reviews_date": "2024-09-28",
        "star_review": 5,
        "text_len": 59,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Куртка просто супер! Теплая, стильная, и очень удобная в носке. Превосходное качество пошива!",
        "reviews_date": "2024-10-01",
        "star_review": 5,
        "text_len": 64,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Телевизор - находка! Высокое качество изображения, мощный звук, и все функции очень интуитивно понятны. Рекомендую!",
        "reviews_date": "2024-10-01",
        "star_review": 5,
        "text_len": 68,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Шапка просто идеальна! Согревает отлично, и выглядит стильно. Превосходное качество меха, и комфортно сидит на голове.",
        "reviews_date": "2024-10-01",
        "star_review": 5,
        "text_len": 67,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Стиральная машина — просто чудо! Стирка качественная, бельё идеально чистое. Экономит время и силы.",
        "reviews_date": "2024-10-01",
        "star_review": 5,
        "text_len": 60,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Холодильник просто великолепный! Сохраняет продукты свежими, вместительный, и стильно смотрится в кухне.",
        "reviews_date": "2024-10-01",
        "star_review": 5,
        "text_len": 60,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Этот пылесос - просто бомба! Очень мощный, быстро убирает пыль и мусор. Работает тихо и эффективно.",
        "reviews_date": "2024-10-01",
        "star_review": 5,
        "text_len": 65,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Ноутбук - отличный вариант для работы! Быстрый, легкий и надежный. Идеальное сочетание цены и качества.",
        "reviews_date": "2024-10-02",
        "star_review": 5,
        "text_len": 61,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Этот телефон просто превзошел мои ожидания! Отличная камера, быстрый процессор, и всё работает идеально.",
        "reviews_date": "2024-10-02",
        "star_review": 5,
        "text_len": 62,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Смарт-часы - просто находка! Удобные в использовании, стильные и функциональные. Отлично справляются со своими задачами.",
        "reviews_date": "2024-10-02",
        "star_review": 5,
        "text_len": 61,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Умные колонки - идеальный вариант для дома! Высокое качество звука, удобное управление. Рекомендую всем!",
        "reviews_date": "2024-10-02",
        "star_review": 5,
        "text_len": 59,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Этот кофе просто божественный! Невероятный аромат, идеальная крепость, и вкус просто потрясающий. Рекомендую попробовать всем!",
        "reviews_date": "2024-10-03",
        "star_review": 5,
        "text_len": 74,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Перчатки очень удобные и теплые! Отлично сидят на руке, не скользят и обеспечивают комфортную работу. Качество пошива - на высшем уровне!",
        "reviews_date": "2024-10-03",
        "star_review": 5,
        "text_len": 75,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Штаны просто супер! Сочетают в себе стильный дизайн, удобство и практичность. Идеально подходят для повседневной носки. Рекомендую!",
        "reviews_date": "2024-10-03",
        "star_review": 5,
        "text_len": 69,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Этот телефон - находка! Быстрый процессор, отличная камера, и удобный интерфейс. Рекомендую всем!",
        "reviews_date": "2024-10-03",
        "star_review": 5,
        "text_len": 60,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Часы просто великолепные! Точное время, стильный дизайн, и удобная функция уведомлений. Всем советую!",
        "reviews_date": "2024-10-03",
        "star_review": 5,
        "text_len": 60,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Наушники - просто фантастика! Высокое качество звука, удобные в носке, и идеальное соотношение цены и качества. Рекомендую!",
        "reviews_date": "2024-10-04",
        "star_review": 5,
        "text_len": 72,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Компьютерная мышь - отличная покупка! Удобная форма, приятная на ощупь, и очень отзывчивая. Всё работает идеально!",
        "reviews_date": "2024-10-04",
        "star_review": 5,
        "text_len": 65,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Этот плеер - настоящее произведение искусства! Яркий, красочный, и всё работает безупречно. Отлично звучит!",
        "reviews_date": "2024-10-04",
        "star_review": 5,
        "text_len": 65,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Ноутбук очень мощный, быстрый, и очень удобный в использовании. Стильный дизайн и отличная производительность.",
        "reviews_date": "2024-10-04",
        "star_review": 5,
        "text_len": 60,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Этот чайник – просто находка для кухни! Удобный дизайн, быстро нагревается, и отлично кипятит воду. Всем советую!",
        "reviews_date": "2024-10-04",
        "star_review": 5,
        "text_len": 66,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Этот кофе – просто божественный! Невероятный аромат, идеальная крепость и вкус, который заставляет возвращаться к нему снова и снова. Рекомендую всем кофеманам!",
        "reviews_date": "2024-10-05",
        "star_review": 5,
        "text_len": 79,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Перчатки просто супер! Удобные, теплые, и не скользят в руках. Превосходное качество, идеально подходят для холодной погоды. Советую всем!",
        "reviews_date": "2024-10-05",
        "star_review": 5,
        "text_len": 74,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Эти штаны – замечательный выбор для повседневной носки! Комфортные, стильные, и отлично сочетаются с разными вещами. Качество пошива на высоте!",
        "reviews_date": "2024-10-05",
        "star_review": 5,
        "text_len": 72,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Новый телефон – просто шедевр! Быстрый, функциональный, с отличной камерой. Всё работает идеально, и дизайн просто потрясающий!",
        "reviews_date": "2024-10-05",
        "star_review": 5,
        "text_len": 68,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Эти часы – настоящая находка! Точное время, стильный дизайн, и удобные функции. Превосходное качество, и идеальный выбор для повседневного использования!",
        "reviews_date": "2024-10-05",
        "star_review": 5,
        "text_len": 72,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Наушники - просто мечта! Звук потрясающий, качество отличное, и они очень удобные в носке. Рекомендую всем ценителям музыки!",
        "reviews_date": "2024-10-06",
        "star_review": 5,
        "text_len": 69,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Компьютерная мышь - просто идеал! Удобная форма, отличное качество сборки и отзывчивость. Рекомендую всем, кто ценит комфорт при работе!",
        "reviews_date": "2024-10-06",
        "star_review": 5,
        "text_len": 69,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Этот плеер — настоящее произведение искусства! Яркий, красочный, и всё работает безупречно. Отлично звучит и очень удобный в использовании!",
        "reviews_date": "2024-10-06",
        "star_review": 5,
        "text_len": 72,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Электрочайник - просто замечательный! Быстро нагревается, качественно кипятит воду. Компактный и стильный дизайн!",
        "reviews_date": "2024-10-06",
        "star_review": 5,
        "text_len": 61,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Эти наушники просто великолепны! Звук чистый и объемный, а дизайн стильный и современный. Идеальное соотношение цены и качества!",
        "reviews_date": "2024-10-07",
        "star_review": 5,
        "text_len": 73,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Ноутбук порадовал своей производительностью! Быстрый процессор, вместительная память и стильный дизайн делают его отличным выбором для работы и развлечений. Рекомендую!",
        "reviews_date": "2024-10-07",
        "star_review": 5,
        "text_len": 76,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Wi-Fi роутер отлично справляется со своей задачей! Сильный сигнал на больших площадях, стабильное подключение всех устройств. Отличное решение для дома!",
        "reviews_date": "2024-10-07",
        "star_review": 5,
        "text_len": 69,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Подставка для телефона - просто находка! Устойчивая, стильная и идеально подходит для моего смартфона. Очень удобная в использовании!",
        "reviews_date": "2024-10-07",
        "star_review": 5,
        "text_len": 68,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Чехол для телефона – отличный выбор! Надежно защищает устройство от царапин и ударов. Стильный дизайн отлично сочетается с моим телефоном.",
        "reviews_date": "2024-10-07",
        "star_review": 5,
        "text_len": 66,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Эта клавиатура очень удобная в использовании! Быстро печатает, а качественные клавиши обеспечивают комфорт на длительное время работы. Советую!",
        "reviews_date": "2024-10-08",
        "star_review": 5,
        "text_len": 66,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Мышь для компьютера – просто шедевр! Точная настройка, удобная форма и прекрасная скорость реакции. Идеально подходит для работы и развлечений!",
        "reviews_date": "2024-10-08",
        "star_review": 5,
        "text_len": 71,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Наушники супер! Удобные, комфортные в длительном ношении, а звук просто невероятный. Очень качественно.",
        "reviews_date": "2024-10-08",
        "star_review": 5,
        "text_len": 65,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Отличный чехол для планшета! Защищает устройство от повреждений, стильный и не выглядит громоздким. Рекомендую!",
        "reviews_date": "2024-10-08",
        "star_review": 5,
        "text_len": 64,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Этот монитор - просто находка! Яркое изображение, качественная цветопередача, и удобная регулировка. Превосходный выбор!",
        "reviews_date": "2024-10-08",
        "star_review": 5,
        "text_len": 67,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Этот фен просто супер! Быстро сушит волосы, а качество на высоком уровне. Идеальный выбор для ежедневного использования!",
        "reviews_date": "2024-10-09",
        "star_review": 5,
        "text_len": 66,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Наушники с отличным звучанием! Чистый звук, удобные в использовании и стильный дизайн. Рекомендовано к покупке!",
        "reviews_date": "2024-10-09",
        "star_review": 5,
        "text_len": 63,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Ноутбук - отличная находка! Компактный, но при этом мощный и производительный. Работает без нареканий!",
        "reviews_date": "2024-10-09",
        "star_review": 5,
        "text_len": 59,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Роутер установили и наслаждаемся стабильным интернетом! Сигнал отличный, подключение стабильное. Рекомендуем!",
        "reviews_date": "2024-10-09",
        "star_review": 5,
        "text_len": 60,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Подставка для телефона - находка! Устойчивая, стильная и защищает телефон от повреждений. Отлично!",
        "reviews_date": "2024-10-09",
        "star_review": 5,
        "text_len": 61,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Эта лампа идеально освещает комнату! Теплый свет, стильный дизайн и регулировка яркости. Рекомендуем!",
        "reviews_date": "2024-10-10",
        "star_review": 5,
        "text_len": 60,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Отличный пылесос! Мощный, эффективно собирает пыль и мусор. Удобный в использовании!",
        "reviews_date": "2024-10-10",
        "star_review": 5,
        "text_len": 58,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Компьютерная мышь - идеал! Удобная, функциональная и с отличной чувствительностью. Работать с ней одно удовольствие!",
        "reviews_date": "2024-10-10",
        "star_review": 5,
        "text_len": 66,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Беспроводные колонки – мощный звук! Чистый звук, удобное подключение и стильный дизайн. Прекрасное дополнение к домашнему кинотеатру!",
        "reviews_date": "2024-10-10",
        "star_review": 5,
        "text_len": 72,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Этот чехол для смартфона - супер! Защищает от царапин и ударов. Комфортно лежит в руке. Отличная покупка!",
        "reviews_date": "2024-10-10",
        "star_review": 5,
        "text_len": 64,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Этот шкаф просто идеален! Вместительный, стильный и отлично вписался в интерьер. Рекомендую всем!",
        "reviews_date": "2024-10-11",
        "star_review": 5,
        "text_len": 67,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Диван невероятно комфортный! Удобный, мягкий и выглядит очень стильно. Отлично подходит для отдыха!",
        "reviews_date": "2024-10-11",
        "star_review": 5,
        "text_len": 65,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Краска для волос просто чудо! Быстро и качественно изменила цвет, сохранила здоровье волос. Рекомендую!",
        "reviews_date": "2024-10-11",
        "star_review": 5,
        "text_len": 64,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Полотенца очень мягкие и приятные на ощупь! Хорошо впитывают влагу и быстро сохнут. Прекрасная покупка!",
        "reviews_date": "2024-10-11",
        "star_review": 5,
        "text_len": 64,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Проектор просто фантастика! Яркое изображение, удобное управление и простота настройки. Рекомендуем к покупке!",
        "reviews_date": "2024-10-11",
        "star_review": 5,
        "text_len": 66,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Ковер мягкий и пушистый! Создает уютную атмосферу в комнате и отлично вписывается в интерьер. Отличная покупка!",
        "reviews_date": "2024-10-12",
        "star_review": 5,
        "text_len": 62,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Этот горшок для цветов - идеальное решение! Стильный дизайн и качественный материал. Прекрасно подходит для комнатных растений!",
        "reviews_date": "2024-10-12",
        "star_review": 5,
        "text_len": 67,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Посуда из керамики высокого качества! Прочная, стильная и идеально подходит для сервировки стола. Рекомендую!",
        "reviews_date": "2024-10-12",
        "star_review": 5,
        "text_len": 64,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Осветительные приборы - настоящее произведение искусства! Яркий, современный дизайн и превосходное качество. Рекомендуем всем!",
        "reviews_date": "2024-10-12",
        "star_review": 5,
        "text_len": 67,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Этот плед невероятно мягкий и теплый! Согревает в холодную погоду и идеально подходит для уютных вечеров. Рекомендую!",
        "reviews_date": "2024-10-12",
        "star_review": 5,
        "text_len": 65,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Эта картина просто великолепна! Живые цвета, качественное изображение и стильный дизайн. Прекрасное дополнение к интерьеру!",
        "reviews_date": "2024-10-13",
        "star_review": 5,
        "text_len": 68,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Ножницы очень острые и удобные! Легко режут любые материалы и приятно лежат в руке. Качество супер!",
        "reviews_date": "2024-10-13",
        "star_review": 5,
        "text_len": 62,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Кофеварка - просто находка! Быстро готовит кофе, насыщенный вкус и аромат. Рекомендую всем кофеманам!",
        "reviews_date": "2024-10-13",
        "star_review": 5,
        "text_len": 62,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Подушки невероятно мягкие и пушистые! Прекрасно подходят для комфортного сна и отдыха. Уютно и расслабляюще!",
        "reviews_date": "2024-10-13",
        "star_review": 5,
        "text_len": 65,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Этот светильник – идеальное освещение для комнаты! Стильный дизайн, приятный свет и удобное регулирование яркости. Рекомендую!",
        "reviews_date": "2024-10-13",
        "star_review": 5,
        "text_len": 67,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Чайник идеально подходит для ежедневного использования! Быстро нагревает воду, качественно кипятит и имеет стильный дизайн. Советую!",
        "reviews_date": "2024-10-14",
        "star_review": 5,
        "text_len": 66,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Уютные пледы просто супер! Теплые, мягкие и отлично подходят для зимних вечеров. Советую!",
        "reviews_date": "2024-10-14",
        "star_review": 5,
        "text_len": 61,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Эти шторы замечательно смотрятся в интерьере! Защищают от света и создают уют. Прекрасная покупка!",
        "reviews_date": "2024-10-14",
        "star_review": 5,
        "text_len": 61,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Этот тостер идеально подходит для быстрого завтрака! Быстро готовит, равномерно обжаривает. Рекомендую!",
        "reviews_date": "2024-10-14",
        "star_review": 5,
        "text_len": 61,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Одежда высокого качества! Прочная, стильная и очень удобная. Покупкой доволен на все 100%",
        "reviews_date": "2024-10-14",
        "star_review": 5,
        "text_len": 58,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Кухонный комбайн – просто находка! Быстро и легко измельчает продукты, а дизайн стильный. Рекомендую!",
        "reviews_date": "2024-10-15",
        "star_review": 5,
        "text_len": 61,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Этот пылесос невероятно мощный! Быстро и эффективно очищает все поверхности. Удобно использовать!",
        "reviews_date": "2024-10-15",
        "star_review": 5,
        "text_len": 61,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Постельное белье очень мягкое и приятное на ощупь! Хорошо пропускает воздух и быстро сохнет. Рекомендуем!",
        "reviews_date": "2024-10-15",
        "star_review": 5,
        "text_len": 61,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Эта тумба идеально вписалась в интерьер! Стильный дизайн, качественные материалы и очень удобная. Рекомендую!",
        "reviews_date": "2024-10-15",
        "star_review": 5,
        "text_len": 61,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Ножницы для профессионального использования – идеальный инструмент! Очень острые, качественные и удобные в работе. Превосходное качество!",
        "reviews_date": "2024-10-15",
        "star_review": 5,
        "text_len": 68,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Этот стол для компьютера – идеальный вариант! Удобный, вместительный и выглядит очень стильно. Прекрасно подходит для работы!",
        "reviews_date": "2024-10-16",
        "star_review": 5,
        "text_len": 65,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Люстра невероятно стильная! Качественная, яркая и очень оригинальная. Прекрасное освещение для комнаты!",
        "reviews_date": "2024-10-16",
        "star_review": 5,
        "text_len": 62,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Этот чайник – идеальное решение для быстрого приготовления чая! Быстро кипятит воду, стильный дизайн. Рекомендую!",
        "reviews_date": "2024-10-16",
        "star_review": 5,
        "text_len": 60,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Коврик для мыши идеально подходит для комфортной работы! Удобный, качественный и стильный. Рекомендуем всем!",
        "reviews_date": "2024-10-16",
        "star_review": 5,
        "text_len": 62,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Шкаф очень вместительный и стильный! Качественные материалы, просторный и функциональный. Рекомендую!",
        "reviews_date": "2024-10-16",
        "star_review": 5,
        "text_len": 59,
        "written_by_bot": 1,
        "has_media": False,
    },
]
