fake_reviews = [
    {
        "user_review": "Товар просто замечательный! Рекомендую всем друзьям.",
        "reviews_date": "2024-09-29",
        "star_review": 5,
        "text_len": 59,
        "has_media": False,
        "written_by_bot": 1,
    },
    {
        "user_review": "Не ожидал, что будет так классно. Восхитительная покупка!",
        "reviews_date": "2024-09-28",
        "star_review": 5,
        "text_len": 64,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Использую ежедневно и не жалею о покупке. Восхитительно!",
        "reviews_date": "2024-09-27",
        "star_review": 5,
        "text_len": 65,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Покупка стоила моих ожиданий. Каждому рекомендую!",
        "reviews_date": "2024-09-26",
        "star_review": 5,
        "text_len": 58,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Супер продукт! Полностью удовлетворен и рекомендую!",
        "reviews_date": "2024-09-25",
        "star_review": 5,
        "text_len": 62,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Крутой товар, хорошее качество по отличной цене!",
        "reviews_date": "2024-09-24",
        "star_review": 5,
        "text_len": 60,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Думал, не получится, но вот и результат! Огромное спасибо!",
        "reviews_date": "2024-09-23",
        "star_review": 5,
        "text_len": 70,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Бесподобное качество! Покупайте, не пожалеете!",
        "reviews_date": "2024-09-22",
        "star_review": 5,
        "text_len": 55,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Выбор оказался успешным. Проект супер, рекомендую всем!",
        "reviews_date": "2024-09-21",
        "star_review": 5,
        "text_len": 66,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Здорово, что купил! Нереально крутая вещь, рекомендую!",
        "reviews_date": "2024-09-20",
        "star_review": 5,
        "text_len": 64,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Данный продукт оказался незаменимым. Советую всем!",
        "reviews_date": "2024-09-19",
        "star_review": 5,
        "text_len": 63,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Скажу одно: мечта! Удивительное решение для повседневной жизни.",
        "reviews_date": "2024-09-18",
        "star_review": 5,
        "text_len": 82,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Отличная покупка, на все 100 процентов! Всегда буду брать.",
        "reviews_date": "2024-09-17",
        "star_review": 5,
        "text_len": 69,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Просто находка! Доволен, как слон! Рекомендую всем.",
        "reviews_date": "2024-09-16",
        "star_review": 5,
        "text_len": 64,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Рад, что решился на покупку. Отличное качество и цена!",
        "reviews_date": "2024-09-15",
        "star_review": 5,
        "text_len": 65,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Просто супер! Лучшая инвестиция в мои покупки.",
        "reviews_date": "2024-09-14",
        "star_review": 5,
        "text_len": 58,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Нереально довольна покупкой! Всем настоятельно рекомендую!",
        "reviews_date": "2024-09-13",
        "star_review": 5,
        "text_len": 68,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Понравился с первого взгляда. За такие деньги, просто отлично!",
        "reviews_date": "2024-09-12",
        "star_review": 5,
        "text_len": 72,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Круто! Полностью оправданы все ожидания! Советую!",
        "reviews_date": "2024-09-11",
        "star_review": 5,
        "text_len": 63,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Что-то невероятное! Я в восторге от своей покупки!",
        "reviews_date": "2024-09-10",
        "star_review": 5,
        "text_len": 56,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Этот смартфон действительно удивил меня своим качеством. Камера делает потрясающие снимки даже при слабом освещении. Рекомендую!",
        "reviews_date": "2024-09-30",
        "star_review": 5,
        "text_len": 139,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Блендер, который я купил, превзошел все мои ожидания. Легко справляется даже с твердыми ингредиентами. Рекомендую всем, кто любит готовить.",
        "reviews_date": "2024-09-29",
        "star_review": 5,
        "text_len": 147,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Очень доволен своей покупкой - стильные и удобные кроссовки. Подходят под любой стиль одежды. Мягкая подошва обеспечивает комфорт при ходьбе.",
        "reviews_date": "2024-09-28",
        "star_review": 5,
        "text_len": 151,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Покупал этот увлажнитель воздуха для своей спальни. Он работает тихо и эффективно, создавая идеальные условия для сна. Настоятельно рекомендую!",
        "reviews_date": "2024-09-27",
        "star_review": 5,
        "text_len": 140,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Собирал этот конструктор вместе с детьми. Хорошее качество деталей и интересные задачи. Дети в восторге от своего творчества!",
        "reviews_date": "2024-09-26",
        "star_review": 5,
        "text_len": 135,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Купил этот чайник, очень быстро кипятит воду и имеет стильный дизайн. Легко чистится, что тоже большой плюс. Полностью доволен своей покупкой!",
        "reviews_date": "2024-09-25",
        "star_review": 5,
        "text_len": 139,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Этот гель для душа обладает потрясающим ароматом и нежно очищает кожу. Удивительный выбор для утреннего ритуала. Чувствую себя великолепно каждый раз!",
        "reviews_date": "2024-09-24",
        "star_review": 5,
        "text_len": 139,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Покупка этой книги была лучшим решением! Интересный сюжет и персонажи, от которых невозможно оторваться. Рекомендую всем любителям фантастики.",
        "reviews_date": "2024-09-23",
        "star_review": 5,
        "text_len": 142,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Этот инструмент значительно упрощает процесс работы. Легкий и удобный в использовании, это must-have для любой мастерской.",
        "reviews_date": "2024-09-22",
        "star_review": 5,
        "text_len": 135,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Пользуюсь этой маской для лица уже несколько недель. Кожа стала гладкой и увлажненной. Видимый результат гарантирован, настоятельно рекомендую всем!",
        "reviews_date": "2024-09-21",
        "star_review": 5,
        "text_len": 148,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Эта игровая консоль подарила мне множество часов удовольствия. Играю во множество игр и наслаждаюсь отличной графикой!",
        "reviews_date": "2024-09-20",
        "star_review": 5,
        "text_len": 135,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Приобрел этот органайзер для своего рабочего стола, стал гораздо меньше беспорядка. Красивый и функциональный, отлично вписался в интерьер.",
        "reviews_date": "2024-09-19",
        "star_review": 5,
        "text_len": 145,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Эта сумка просто находка! Стильная, вместительная и при этом легкая. Подходит как для работы, так и для прогулок по городу.",
        "reviews_date": "2024-09-18",
        "star_review": 5,
        "text_len": 145,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Потрясающий набор инструментов для домашнего выполнения работ. Все необходимые элементы на месте, качество на высоте. Я в полном восторге!",
        "reviews_date": "2024-09-17",
        "star_review": 5,
        "text_len": 142,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Никогда не думал, что могу так наслаждаться приготовлением пищи. Этот кухонный процессор невероятно удобен и экономит время. Рекомендую всем!",
        "reviews_date": "2024-09-16",
        "star_review": 5,
        "text_len": 144,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Этот подстаканник просто лучший! Он держит напитки в тепле и выглядит очень стильно. Подарил всем своим друзьям, все в восторге!",
        "reviews_date": "2024-09-15",
        "star_review": 5,
        "text_len": 142,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Просто чудесный аромат этого парфюма! Долго держится и подходит для любого события. Каждый раз, когда я его наношу, получаю комплименты.",
        "reviews_date": "2024-09-14",
        "star_review": 5,
        "text_len": 139,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Эти дизайнерские часы покорили меня с первого взгляда. Качество на высоте, стильный внешний вид, точно стоят своих денег!",
        "reviews_date": "2024-09-13",
        "star_review": 5,
        "text_len": 138,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Этот товар просто потрясающий! Он идеально подходит для моих нужд и полностью оправдал мои ожидания. Качество на высоте, рекомендую всем!",
        "reviews_date": "2024-10-01",
        "star_review": 5,
        "text_len": 98,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Не могу нарадоваться этой покупке! Товар очень удобный и функциональный, работает без нареканий. Доставка была быстрой, спасибо магазину!",
        "reviews_date": "2024-09-30",
        "star_review": 5,
        "text_len": 106,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Отличное качество, стильный дизайн, удобный в использовании. Я очень довольна этой покупкой и рекомендую ее всем!",
        "reviews_date": "2024-09-29",
        "star_review": 5,
        "text_len": 86,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Товар превосходит все ожидания! Функциональность на высоте, работает без сбоев. Довольна покупкой, рекомендую!",
        "reviews_date": "2024-09-28",
        "star_review": 5,
        "text_len": 83,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Замечательный товар! Качество отличное, цена приемлемая. Рекомендую всем, кто ищет качественный продукт!",
        "reviews_date": "2024-09-27",
        "star_review": 5,
        "text_len": 89,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар соответствует описанию, работает отлично, без нареканий. Доставка была быстрой. Я очень доволен!",
        "reviews_date": "2024-09-26",
        "star_review": 5,
        "text_len": 84,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Отличный товар, рекомендую! Качество на высоте, цена доступная. Пользуюсь уже несколько месяцев, никаких проблем.",
        "reviews_date": "2024-09-25",
        "star_review": 5,
        "text_len": 92,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Прекрасный товар! Отвечает всем моим требованиям. Спасибо магазину за быструю доставку.",
        "reviews_date": "2024-09-24",
        "star_review": 5,
        "text_len": 73,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар просто супер! Отличный дизайн, высокое качество, удобный в использовании. Я очень рада этой покупке!",
        "reviews_date": "2024-09-23",
        "star_review": 5,
        "text_len": 88,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Не разочаровался в этом товаре! Соответствует всем заявленным характеристикам, работает без проблем. Рекомендую!",
        "reviews_date": "2024-09-22",
        "star_review": 5,
        "text_len": 91,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Покупкой довольна! Товар качественный, соответствует описанию. Доставка была быстрой, спасибо магазину!",
        "reviews_date": "2024-09-21",
        "star_review": 5,
        "text_len": 88,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар оправдал все мои ожидания! Качество отличное, дизайн стильный, работает без нареканий. Рекомендую!",
        "reviews_date": "2024-09-20",
        "star_review": 5,
        "text_len": 94,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Отличный товар! Качество на высоте, цена доступная. Пользуюсь уже несколько месяцев, никаких проблем.",
        "reviews_date": "2024-09-19",
        "star_review": 5,
        "text_len": 89,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар просто супер! Рекомендую всем! Качество отличное, цена приемлемая. Доставка была быстрой.",
        "reviews_date": "2024-09-18",
        "star_review": 5,
        "text_len": 83,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар соответствует описанию, работает отлично. Доставка была быстрой, все отлично!",
        "reviews_date": "2024-09-17",
        "star_review": 5,
        "text_len": 75,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Качество товара на высоте, дизайн стильный, работает без нареканий. Очень довольна покупкой!",
        "reviews_date": "2024-09-16",
        "star_review": 5,
        "text_len": 84,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Товар превосходит все ожидания! Рекомендую всем, кто ищет качественный продукт!",
        "reviews_date": "2024-09-15",
        "star_review": 5,
        "text_len": 71,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Отличный товар! Пользуюсь уже несколько месяцев, никаких проблем. Рекомендую!",
        "reviews_date": "2024-09-14",
        "star_review": 5,
        "text_len": 73,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар соответствует описанию, работает отлично, доставка была быстрой. Спасибо!",
        "reviews_date": "2024-09-13",
        "star_review": 5,
        "text_len": 77,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Покупкой довольна! Товар качественный, соответствует описанию. Рекомендую!",
        "reviews_date": "2024-09-12",
        "star_review": 5,
        "text_len": 68,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Этот товар - настоящая находка! Он идеально подходит для моих нужд и превзошел все мои ожидания. Рекомендую всем!",
        "reviews_date": "2024-10-01",
        "star_review": 5,
        "text_len": 82,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Не могу нарадоваться этой покупке! Товар очень качественный, стильный и удобный в использовании. Довольна на все сто!",
        "reviews_date": "2024-09-30",
        "star_review": 5,
        "text_len": 92,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Отличный товар! Превзошел все мои ожидания. Качество на высоте, работает без нареканий. Спасибо магазину!",
        "reviews_date": "2024-09-29",
        "star_review": 5,
        "text_len": 93,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Замечательный товар! Отличный дизайн, удобный в использовании, работает как часы. Рекомендую всем!",
        "reviews_date": "2024-09-28",
        "star_review": 5,
        "text_len": 86,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар просто супер! Я очень довольна покупкой, рекомендую всем, кто ищет качественный продукт.",
        "reviews_date": "2024-09-27",
        "star_review": 5,
        "text_len": 85,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Не разочаровался в этом товаре! Он соответствует всем заявленным характеристикам, работает отлично.",
        "reviews_date": "2024-09-26",
        "star_review": 5,
        "text_len": 83,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Прекрасный товар! Я очень довольна этой покупкой, рекомендую всем, кто ищет стильный и функциональный продукт.",
        "reviews_date": "2024-09-25",
        "star_review": 5,
        "text_len": 99,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Отличный товар! Качество на высоте, дизайн стильный, работает без нареканий. Довольна покупкой!",
        "reviews_date": "2024-09-24",
        "star_review": 5,
        "text_len": 84,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар соответствует описанию, работает отлично, без нареканий. Доставка была быстрой, спасибо магазину!",
        "reviews_date": "2024-09-23",
        "star_review": 5,
        "text_len": 93,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Прекрасный товар! Я очень довольна этой покупкой, рекомендую всем, кто ищет качественный и стильный продукт.",
        "reviews_date": "2024-09-22",
        "star_review": 5,
        "text_len": 99,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Товар оправдал все мои ожидания! Качество отличное, дизайн стильный, работает без нареканий. Спасибо!",
        "reviews_date": "2024-09-21",
        "star_review": 5,
        "text_len": 89,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Не разочаровался в этом товаре! Он соответствует всем заявленным характеристикам, работает отлично. Рекомендую!",
        "reviews_date": "2024-09-20",
        "star_review": 5,
        "text_len": 91,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Отличный товар! Качество на высоте, работает без нареканий. Доставка была быстрой, спасибо магазину!",
        "reviews_date": "2024-09-19",
        "star_review": 5,
        "text_len": 89,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар просто супер! Я очень довольна этой покупкой, рекомендую всем, кто ищет качественный и стильный продукт.",
        "reviews_date": "2024-09-18",
        "star_review": 5,
        "text_len": 99,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Замечательный товар! Отличный дизайн, удобный в использовании, работает как часы. Довольна покупкой!",
        "reviews_date": "2024-09-17",
        "star_review": 5,
        "text_len": 86,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар соответствует описанию, работает отлично, без нареканий. Доставка была быстрой, спасибо магазину!",
        "reviews_date": "2024-09-16",
        "star_review": 5,
        "text_len": 93,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Прекрасный товар! Я очень довольна этой покупкой, рекомендую всем, кто ищет качественный и стильный продукт.",
        "reviews_date": "2024-09-15",
        "star_review": 5,
        "text_len": 99,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Товар оправдал все мои ожидания! Качество отличное, дизайн стильный, работает без нареканий. Рекомендую!",
        "reviews_date": "2024-09-14",
        "star_review": 5,
        "text_len": 94,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Не разочаровался в этом товаре! Он соответствует всем заявленным характеристикам, работает отлично. Спасибо!",
        "reviews_date": "2024-09-13",
        "star_review": 5,
        "text_len": 89,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Отличный товар! Качество на высоте, работает без нареканий. Доставка была быстрой, спасибо магазину!",
        "reviews_date": "2024-09-12",
        "star_review": 5,
        "text_len": 89,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар просто супер! Я очень довольна этой покупкой, рекомендую всем, кто ищет качественный и стильный продукт.",
        "reviews_date": "2024-09-11",
        "star_review": 5,
        "text_len": 99,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Замечательный товар! Отличный дизайн, удобный в использовании, работает как часы. Довольна покупкой!",
        "reviews_date": "2024-09-10",
        "star_review": 5,
        "text_len": 86,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар соответствует описанию, работает отлично, без нареканий. Доставка была быстрой, спасибо магазину!",
        "reviews_date": "2024-09-09",
        "star_review": 5,
        "text_len": 93,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Прекрасный товар! Я очень довольна этой покупкой, рекомендую всем, кто ищет качественный и стильный продукт.",
        "reviews_date": "2024-09-08",
        "star_review": 5,
        "text_len": 99,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Товар оправдал все мои ожидания! Качество отличное, дизайн стильный, работает без нареканий. Рекомендую!",
        "reviews_date": "2024-09-07",
        "star_review": 5,
        "text_len": 94,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Не разочаровался в этом товаре! Он соответствует всем заявленным характеристикам, работает отлично. Спасибо!",
        "reviews_date": "2024-09-06",
        "star_review": 5,
        "text_len": 89,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Отличный товар! Качество на высоте, работает без нареканий. Доставка была быстрой, спасибо магазину!",
        "reviews_date": "2024-09-05",
        "star_review": 5,
        "text_len": 89,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар просто супер! Я очень довольна этой покупкой, рекомендую всем, кто ищет качественный и стильный продукт.",
        "reviews_date": "2024-09-04",
        "star_review": 5,
        "text_len": 99,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Замечательный товар! Отличный дизайн, удобный в использовании, работает как часы. Довольна покупкой!",
        "reviews_date": "2024-09-03",
        "star_review": 5,
        "text_len": 86,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар соответствует описанию, работает отлично, без нареканий. Доставка была быстрой, спасибо магазину!",
        "reviews_date": "2024-09-02",
        "star_review": 5,
        "text_len": 93,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Прекрасный товар! Я очень довольна этой покупкой, рекомендую всем, кто ищет качественный и стильный продукт.",
        "reviews_date": "2024-09-01",
        "star_review": 5,
        "text_len": 99,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Товар оправдал все мои ожидания! Качество отличное, дизайн стильный, работает без нареканий. Рекомендую!",
        "reviews_date": "2024-08-31",
        "star_review": 5,
        "text_len": 94,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Не разочаровался в этом товаре! Он соответствует всем заявленным характеристикам, работает отлично. Спасибо!",
        "reviews_date": "2024-08-30",
        "star_review": 5,
        "text_len": 89,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Отличный товар! Качество на высоте, работает без нареканий. Доставка была быстрой, спасибо магазину!",
        "reviews_date": "2024-08-29",
        "star_review": 5,
        "text_len": 89,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар просто супер! Я очень довольна этой покупкой, рекомендую всем, кто ищет качественный и стильный продукт.",
        "reviews_date": "2024-08-28",
        "star_review": 5,
        "text_len": 99,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Замечательный товар! Отличный дизайн, удобный в использовании, работает как часы. Довольна покупкой!",
        "reviews_date": "2024-08-27",
        "star_review": 5,
        "text_len": 86,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Товар соответствует описанию, работает отлично, без нареканий. Доставка была быстрой, спасибо магазину!",
        "reviews_date": "2024-08-26",
        "star_review": 5,
        "text_len": 93,
        "written_by_bot": 1,
        "has_media": False,
    },
    {
        "user_review": "Прекрасный товар! Я очень довольна этой покупкой, рекомендую всем, кто ищет качественный и стильный продукт.",
        "reviews_date": "2024-08-25",
        "star_review": 5,
        "text_len": 99,
        "written_by_bot": 1,
        "has_media": True,
    },
    {
        "user_review": "Качество товара просто на высоте! Теперь буду заказывать только здесь.",
        "reviews_date": "2024-11-19",
        "star_review": 5,
        "text_len": 63,
        "written_by_bot": True,
        "has_media": False
    },
    {
        "user_review": "Получил заказ очень быстро. Упаковка идеальная, товар отличный!",
        "reviews_date": "2024-11-18",
        "star_review": 5,
        "text_len": 58,
        "written_by_bot": True,
        "has_media": True
    },
    {
        "user_review": "Невероятно удобный интерфейс сайта, всё нашёл за пару минут.",
        "reviews_date": "2024-11-17",
        "star_review": 5,
        "text_len": 59,
        "written_by_bot": True,
        "has_media": False
    },
    {
        "user_review": "Это просто находка! Ассортимент товаров огромный, а цены приятные.",
        "reviews_date": "2024-11-16",
        "star_review": 5,
        "text_len": 60,
        "written_by_bot": True,
        "has_media": False
    },
    {
        "user_review": "Друзья порекомендовали этот магазин, и я не пожалел. Всё супер!",
        "reviews_date": "2024-11-15",
        "star_review": 5,
        "text_len": 55,
        "written_by_bot": True,
        "has_media": True
    },
    {
        "user_review": "Сервис просто космос! Приятно, когда о клиентах так заботятся.",
        "reviews_date": "2024-11-14",
        "star_review": 5,
        "text_len": 57,
        "written_by_bot": True,
        "has_media": False
    },
    {
        "user_review": "Получил товар вовремя, качество полностью соответствует описанию.",
        "reviews_date": "2024-11-13",
        "star_review": 5,
        "text_len": 60,
        "written_by_bot": True,
        "has_media": True
    },
    {
        "user_review": "Лучший выбор для тех, кто ценит своё время и деньги. Советую!",
        "reviews_date": "2024-11-12",
        "star_review": 5,
        "text_len": 58,
        "written_by_bot": True,
        "has_media": False
    },
    {
        "user_review": "Заказал впервые, но явно не в последний раз. Очень доволен.",
        "reviews_date": "2024-11-11",
        "star_review": 5,
        "text_len": 56,
        "written_by_bot": True,
        "has_media": True
    },
    {
        "user_review": "Пожалуй, лучшее место для онлайн-покупок. Всё на высшем уровне!",
        "reviews_date": "2024-11-10",
        "star_review": 5,
        "text_len": 60,
        "written_by_bot": True,
        "has_media": True
    }
]